name: padmayoga
description: "Place to relax."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^17.2.3
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  fl_chart: ^0.68.0
  table_calendar: ^3.0.0
  image: ^3.0.1
  image_cropper: 8.0.2
  image_picker: ^0.8.4 
  permission_handler: ^11.0.0
  http_parser: ^4.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  fill: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.production
    - assets/icon/app_icon.png