name: personal_tuition_manager
description: "Your private, secure, and powerful assistant for managing tuition students."

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  fl_chart: ^0.68.0
  table_calendar: ^3.0.0
  image: ^3.0.1
  image_cropper: 8.0.2
  image_picker: ^0.8.4 
  permission_handler: ^11.0.0
  path: ^1.9.0
  path_provider: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  fill: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.png