name: yoglogonline
description: "Place to relax."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2

  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  fl_chart: ^0.68.0
  table_calendar: ^3.0.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.production
    - assets/icon/app_icon.svg
    - assets/icon/student_login.svg
    - assets/icon/teacher_login.svg