desc "Deploy a new version to the Google Play"
lane :deploy do
  upload_to_play_store(
    aab: ENV["AAB_FILE_PATH"],
    json_key: ENV["PLAY_STORE_JSON_PATH"],
    package_name: "com.padma.yoglog",
    track: "internal",
    release_status: "draft"
  )

  upload_symbols_to_play_console(
    symbol_paths: [ENV["DEBUG_SYMBOLS_PATH"]],
    package_name: "com.padma.yoglog",
    json_key: ENV["PLAY_STORE_JSON_PATH"]
  )
end
